### ISSUE TITLE
Could not reproduce Visualization HW results.

### ISSUE THREAD

**Issue by bgurkas** [UC-Irvine-CS175/final-project-tea-cells#4]
Visualization graphics could not be reproduced.

## Steps Taken:
1) Run pca_tsne.py

## Issues Encountered:
1) Boto3 response returns NULL
2) TypeError:
![image](https://github.com/UC-Irvine-CS175/final-project-tea-cells/assets/80727381/1fd1e548-93e2-49e3-b21f-74443f47c6aa)

**Comment by Pagazone-Pan** [comment]
did you run bps_datamodule before that? It is necessary for your pcs_tsne to work

**Comment by bgurkas** [comment]
Solved by running dependencies first.
